/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Pritika
 */
public class Communityview extends javax.swing.JPanel {

    /**
     * Creates new form Communityview
     */
    Communitydetailslist dict;
    
    public Communityview(Communitydetailslist dict) {
        initComponents();
        this.dict=dict;
        Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcomview = new javax.swing.JTable();
        btnsearch = new javax.swing.JButton();
        btnview = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        lblsearchby = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();

        tblcomview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NAME", "AGE", "GENDER", "RESIDENCE", "CITY", "COMMUNITY", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblcomview);

        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnview.setText("VIEW");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        lblsearchby.setText("SEARCH BY");

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblsearchby, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsearch)
                        .addGap(134, 134, 134)
                        .addComponent(btnview)
                        .addGap(57, 57, 57)
                        .addComponent(btndelete)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsearch)
                    .addComponent(btnview)
                    .addComponent(btndelete)
                    .addComponent(lblsearchby)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 247, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblcomview.getSelectedRow();
        if(selectedrow < 0)
        {
            JOptionPane.showMessageDialog(this, "Select a row to Delete");
        }
        else
        {
            DefaultTableModel model =(DefaultTableModel) tblcomview.getModel();
            Communitydetails emp = (Communitydetails)model.getValueAt(selectedrow,6);
            dict.deleteCommunitydetails(emp);
            JOptionPane.showMessageDialog(this, "Record deleted Successfully");
            Table();
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        
       if(txtsearch.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Enter field to Search");
        }
        else
        {
            search(txtsearch.getText());
        }
    }//GEN-LAST:event_btnsearchActionPerformed
public void search(String str)
    {
        DefaultTableModel model = (DefaultTableModel) tblcomview.getModel();
        TableRowSorter<DefaultTableModel> s = new TableRowSorter<>(model);
        tblcomview.setRowSorter(s);
        s.setRowFilter(RowFilter.regexFilter(str));
        
    }
    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:
      int selectedrow = tblcomview.getSelectedRow();
        if(selectedrow < 0)
        {
            JOptionPane.showMessageDialog(this, "Select a row to View");
            
        }
        else
        {
            DefaultTableModel model = (DefaultTableModel) tblcomview.getModel();
            Communitydetails emp = (Communitydetails)model.getValueAt(selectedrow,6);
            Communityadminupdate communityadminupdate = new Communityadminupdate(emp,dict);
            communityadminupdate.setVisible(true);
            
            
        }
            
    }//GEN-LAST:event_btnviewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnview;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblsearchby;
    private javax.swing.JTable tblcomview;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

   private void Table()
   {
       DefaultTableModel model = (DefaultTableModel) tblcomview.getModel();
       model.setRowCount(0);
       for (Communitydetails emp: dict.getCommunitydetailsinfo())
       {
           Object[] row=new Object[7];
           row[0]=emp.getName();
           row[1]=emp.getAge();
           row[2]=emp.getGender();
           row[3]=emp.getResidence();
           row[4]=emp.getCity();
           row[5]=emp.getCommunity();
           row[6]=emp;
           model.addRow(row);
       }
   }
}
